name: Android Dependency Graph

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
        
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
      
    steps:
    
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Generate Dependency Graph
      run: ./gradlew projectDependencyGraph

    - name: Commit
      run: |
        git config --local user.email 'action@github.com'
        git config --local user.name 'GitHub Action'
        git diff --quiet && git diff --staged --quiet || git commit -am 'Update dependency graph'

    - name: Push
      uses: ad-m/github-push-action@v0.7.0
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
