name: Android Dependency Graph

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
        
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
      
    steps:
    
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin' 
        java-version: '17'

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v1

    - name: Generate Dependency Graph
      run: ./gradlew projectDependencyGraph

    - name: Commit
      run: |
        git config --local user.email 'action@github.com'
        git config --local user.name 'GitHub Action'
        git add .
        git commit -m "Update dependency graph"
        git push
